services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - .env.local
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
    mongodb_data: